require("abc")
require("argparse")
require("base64")
require("cmd")
require("contextlib")
require("copy")
require("datetime")
require("fnmatch")
require("functools")
require("gzip")
require("hmac")
require("html")
require("inspect")
require("itertools")
require("locale")
require("logging")
require("operator")
require("pathlib")
require("pickle")
require("pprint")
require("quopri")
require("string")
require("struct")
require("textwrap")
require("time")
require("traceback")
require("unittest")
require("uu")
require("venv")
require("warnings")

# NOTE:SnoopJ:these aren't packages and require special handling
freeze("$(MPY_LIB_DIR)/python-stdlib/bisect", "bisect.py")
freeze("$(MPY_LIB_DIR)/python-stdlib/keyword", "keyword.py")
freeze("$(MPY_LIB_DIR)/python-stdlib/types", "types.py")

# NOTE:SnoopJ:these are already available, we don't need to include them again
# require("json")
# require("os")

# NOTE:SnoopJ:the following stdlib modules are excluded because they're largely
# not useful in a build with VFS disabled
# require("pkg_resources")
# require("pkgutil")
# require("shutil")
# require("ssl")
# require("stat")
# require("tempfile")
# require("threading")
